[client]
toolbarMode = "minimal"
showErrorDetails = false

[theme]
base = "light"
primaryColor = "#1d4ed8"
backgroundColor = "#f8faff"
secondaryBackgroundColor = "#eff6ff"
textColor = "#1e293b"
font = "sans serif"
